const sampleListings = [
  {
    title: "Cozy Mountain Cabin",
    description: "Rustic cabin surrounded by towering pine trees and scenic trails.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    },
    price: 1200,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Luxury Urban Penthouse",
    description: "High-rise penthouse with sweeping city views and modern decor.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1560448204-603b3fc33dda",
    },
    price: 3500,
    location: "New York",
    country: "United States",
  },
  {
    title: "Charming Cottage by the Lake",
    description: "Quaint cottage with stunning lake views and private dock.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 1500,
    location: "Vermont",
    country: "United States",
  },
  {
    title: "Seaside Villa with Infinity Pool",
    description: "Lavish villa overlooking the ocean with an infinity pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    },
    price: 4000,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Modern Farmhouse Retreat",
    description: "Spacious farmhouse with rolling green hills and farm animals.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1551218808-94e220e084d2",
    },
    price: 1700,
    location: "Napa Valley",
    country: "United States",
  },
  {
    title: "Historic Castle Stay",
    description: "Experience royal luxury in a beautifully preserved medieval castle.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1559067090-41f6c2b09f38",
    },
    price: 4500,
    location: "Edinburgh",
    country: "Scotland",
  },
  {
    title: "Treehouse Adventure",
    description: "Unique treehouse nestled high in the forest canopy.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    },
    price: 900,
    location: "Costa Rica",
    country: "Costa Rica",
  },
  {
    title: "Elegant Parisian Loft",
    description: "Chic loft in the heart of Paris with Eiffel Tower views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1521747116042-5a810fda9664",
    },
    price: 3200,
    location: "Paris",
    country: "France",
  },
  {
    title: "Beachfront Bungalow",
    description: "Relaxing beachfront bungalow just steps from the shore.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    },
    price: 2600,
    location: "Maui",
    country: "United States",
  },
  {
    title: "Ski Chalet Escape",
    description: "Warm and cozy ski chalet with easy access to slopes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1517849845537-4d257902454a",
    },
    price: 2800,
    location: "Swiss Alps",
    country: "Switzerland",
  },
  {
    title: "Desert Oasis Villa",
    description: "A luxury desert villa with private pool and stunning views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    },
    price: 3500,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Tropical Overwater Bungalow",
    description: "Experience paradise in this overwater bungalow with ocean access.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    },
    price: 5000,
    location: "Maldives",
    country: "Maldives",
  },
  {
    title: "Hilltop Vineyard Villa",
    description: "Peaceful villa overlooking vineyards and olive groves.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    },
    price: 3100,
    location: "Tuscany",
    country: "Italy",
  },
  {
    title: "Scandinavian Lakeside Cabin",
    description: "Minimalist cabin with lakeside views and sauna.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    },
    price: 1800,
    location: "Sweden",
    country: "Sweden",
  },
  {
    title: "Jungle Lodge",
    description: "Immersed in nature, this lodge offers a unique jungle experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    },
    price: 1700,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Luxury Mountain Lodge",
    description: "Stunning mountain lodge with sweeping views and top-tier amenities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1560810213-d82e16b195d7",
    },
    price: 3000,
    location: "Whistler",
    country: "Canada",
  },
  {
    title: "Tropical Rainforest Villa",
    description: "A secluded villa in the heart of the rainforest with modern amenities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1580281659037-5270534415b0",
    },
    price: 3800,
    location: "Costa Rica",
    country: "Costa Rica",
  },
  {
    title: "Palace in the Sky",
    description: "Opulent penthouse located at the top of a skyscraper with panoramic city views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1519279612475-d3f0d68fdd6b",
    },
    price: 5000,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Secluded Island Retreat",
    description: "Private island escape with beach access and luxurious amenities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1484172696994-3b7e100dd379",
    },
    price: 7000,
    location: "Fiji",
    country: "Fiji",
  },
  {
    title: "Minimalist Urban Loft",
    description: "Stylish, minimalist loft with a unique blend of modern and industrial design.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1563206760-542f052928a4",
    },
    price: 2400,
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "Glamorous Beachfront Mansion",
    description: "A luxurious mansion just steps away from the beach, with incredible sunset views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1528623501391-dad450bd772d",
    },
    price: 8000,
    location: "Miami",
    country: "United States",
  },
  {
    title: "Tropical Cliffside Villa",
    description: "Exclusive villa perched on a cliff with breathtaking ocean views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1544282492-2b4e9223de28",
    },
    price: 6000,
    location: "Hawaii",
    country: "United States",
  },
  {
    title: "Waterfront Estate",
    description: "Elegant estate located on the water's edge, with expansive gardens.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1587764414364-b163b89bc95f",
    },
    price: 5500,
    location: "Vancouver",
    country: "Canada",
  },
  {
    title: "Luxury Ski-in/Ski-out Chalet",
    description: "Chalet right on the slopes with high-end amenities and private ski lift.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552427993-849ecf3568fa",
    },
    price: 7000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Lakefront Mansion",
    description: "Gorgeous mansion on the shores of a pristine lake, with a private dock.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1555715261-58613d7b7585",
    },
    price: 6000,
    location: "Geneva",
    country: "Switzerland",
  },
  {
    title: "Desert Escape Villa",
    description: "A luxurious villa surrounded by the serenity of the desert landscape.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566811676-b0c07e5a2cfa",
    },
    price: 3200,
    location: "Arizona",
    country: "United States",
  },
  {
    title: "Alpine Escape Chalet",
    description: "Chalet nestled in the Alps with an open fireplace and panoramic views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518313934654-d51e77242bc4",
    },
    price: 4000,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "Seaside Cliff Mansion",
    description: "A magnificent cliffside mansion with direct beach access and stunning views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1603720719334-3dba3e0e9888",
    },
    price: 9000,
    location: "Cape Town",
    country: "South Africa",
  },
  {
    title: "Mountain View Villa",
    description: "Luxurious villa with unobstructed views of the mountain range and private gardens.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1519860910435-eae2b46e1b1a",
    },
    price: 5500,
    location: "Colorado",
    country: "United States",
  }
];

module.exports = { data: sampleListings };